#include "Ast.h"
#include "SymbolTable.h"
#include "Unit.h"
#include "Instruction.h"
#include "IRBuilder.h"
#include <string>
#include "Type.h"

extern FILE *yyout;
int Node::counter = 0;
IRBuilder* Node::builder = nullptr;

Node::Node()
{
    seq = counter++;
}

void Node::backPatch(std::vector<Instruction*> &list, BasicBlock*bb)
{
    for(auto &inst:list)
    {
        if(inst->isCond())
            dynamic_cast<CondBrInstruction*>(inst)->setTrueBranch(bb);
        else if(inst->isUncond())
            dynamic_cast<UncondBrInstruction*>(inst)->setBranch(bb);
    }
}

std::vector<Instruction*> Node::merge(std::vector<Instruction*> &list1, std::vector<Instruction*> &list2)
{
    std::vector<Instruction*> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit *unit)
{
    IRBuilder *builder = new IRBuilder(unit);
    Node::setIRBuilder(builder);
    root->genCode();
}

void FunctionDef::genCode()
{
    Unit *unit = builder->getUnit();
    Function *func = new Function(unit, se);
    BasicBlock *entry = func->getEntry();
    // set the insert point to the entry basicblock of this function.
    builder->setInsertBB(entry);

    stmt->genCode();

    /**
     * Construct control flow graph. You need do set successors and predecessors for each basic block.
     * Todo
    */
   
}

void BinaryExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Function *func = bb->getParent();
    if (op == AND)
    {
        BasicBlock *trueBB = new BasicBlock(func);  // if the result of lhs is true, jump to the trueBB.
        expr1->genCode();
        backPatch(expr1->trueList(), trueBB);
        builder->setInsertBB(trueBB);               // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = expr2->trueList();
        false_list = merge(expr1->falseList(), expr2->falseList());
    }
    else if(op == OR)
    {
        // Todo
    }
    else if(op >= LESS && op <= GREATER)
    {
        // Todo
    }
    else if(op >= ADD && op <= SUB)
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case ADD:
            opcode = BinaryInstruction::ADD;
            break;
        case SUB:
            opcode = BinaryInstruction::SUB;
            break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
}

void Constant::genCode()
{
    // we don't need to generate code.
}

void Id::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getAddr();
    new LoadInstruction(dst, addr, bb);
}

void IfStmt::genCode()
{
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(end_bb);
}

void IfElseStmt::genCode()
{
    // Todo
}

void CompoundStmt::genCode()
{
    // Todo
}

void SeqNode::genCode()
{
    // Todo
}

void DeclStmt::genCode()
{
    IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(id->getSymPtr());
    if(se->isGlobal())
    {
        Operand *addr;
        SymbolEntry *addr_se;
        addr_se = new IdentifierSymbolEntry(*se);
        addr_se->setType(new PointerType(se->getType()));
        addr = new Operand(addr_se);
        se->setAddr(addr);
    }
    else if(se->isLocal())
    {
        Function *func = builder->getInsertBB()->getParent();
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;
        Operand *addr;
        SymbolEntry *addr_se;
        Type *type;
        type = new PointerType(se->getType());
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
        addr = new Operand(addr_se);
        alloca = new AllocaInstruction(addr, se);                   // allocate space for local id in function stack.
        entry->insertFront(alloca);                                 // allocate instructions should be inserted into the begin of the entry block.
        se->setAddr(addr);                                          // set the addr operand in symbol entry so that we can use it in subsequent code generation.
    }
}

void ReturnStmt::genCode()
{
    // Todo
}

void AssignStmt::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    expr->genCode();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(lval->getSymPtr())->getAddr();
    Operand *src = expr->getOperand();
    /***
     * We haven't implemented array yet, the lval can only be ID. So we just store the result of the `expr` to the addr of the id.
     * If you want to implement array, you have to caculate the address first and then store the result into it.
     */
    new StoreInstruction(addr, src, bb);
}

void Ast::typeCheck()
{
    if(root != nullptr)
        root->typeCheck();
}

void FunctionDef::typeCheck()
{
    // Todo
}

void BinaryExpr::typeCheck()
{
    // Todo
}

void Constant::typeCheck()
{
    // Todo
}

void Id::typeCheck()
{
    // Todo
}

void IfStmt::typeCheck()
{
    // Todo
}

void IfElseStmt::typeCheck()
{
    // Todo
}

void CompoundStmt::typeCheck()
{
    // Todo
}

void SeqNode::typeCheck()
{
    // Todo
}

void DeclStmt::typeCheck()
{
    // Todo
}

void ReturnStmt::typeCheck()
{
    // Todo
}

void AssignStmt::typeCheck()
{
    // Todo
}


void Ast::output()
{
    fprintf(yyout, "program\n");
    if(root != nullptr)
        root->output(4);
}

void BinaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        case ADD:
            op_str = "add";
            break;
        case SUB:
            op_str = "sub";
            break;
        case LOGIC_AND:
            op_str = "logic_and";
            break;
        case LOGIC_OR:
            op_str = "logic_or";
            break;
        case LESS:
            op_str = "less";
            break;
        case GREATER:
            op_str = "greater";
            break;
        case LESS_EQUAL:
            op_str = "less_equal";
            break;
        case GREATER_EQUAL:
            op_str = "greater_equal";
            break;
        case EQUAL_TO:
            op_str = "equal_to";
            break;
        case NOT_EQUAL_TO:
            op_str = "not_equal_to";
            break;
        case PRODUCT:
            op_str = "mul";
            break;
        case DIVISION:
            op_str = "div";
            break;
        case REMAINDER:
            op_str = "mod";
            break;
    }
    fprintf(yyout, "%*cBinaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr1->output(level + 4);
    expr2->output(level + 4);
}

void UnaryExpr::output(int level)
{
    std::string op_str;
    switch (op)
    {
        case SUB:
            op_str = "neg";
            break;
        case LOGIC_NOT:
            op_str = "logic_not";
            break;
    }
    fprintf(yyout,"%*cUnaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr->output(level + 4);
}


void Constant::output(int level)
{
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    //q6浮点数支持
    if(symbolEntry->getType()->isInt())
        fprintf(yyout, "%*cIntegerLiteral\tvalue: %s\ttype: %s\n", level, ' ',
                value.c_str(), type.c_str());
    else
        fprintf(yyout, "%*cFloatLiteral\tvalue: %s\ttype: %s\n", level, ' ',
                value.c_str(), type.c_str());
}

void Id::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}
//q14数组取值
void ArrayIndex::output(int level)
{
    std::string name, type;
    int scope;
    name = arrDef->toStr();
    type = symbolEntry->getType()->toStr();
    // scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    scope = dynamic_cast<IdentifierSymbolEntry*>(arrDef)->getScope();
    fprintf(yyout, "%*cArrayValue\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
    dim->output(level + 4);
}

//q12函数调用
void FuncCall::output(int level){
    fprintf(yyout, "%*cFunctionCall function name: %s, type: %s\n", level, ' ', 
            funcDef->toStr().c_str(), funcDef->getType()->toStr().c_str());
    for (auto i:arg){
        i->output(level + 4);
    }
}

void EmptyStmt::output(int level)
{
    fprintf(yyout, "%*cEmptyStmt\n", level, ' ');
}
void ExprStmt::output(int level)
{
    exp->output(level + 4);
}

void BreakStmt::output(int level)
{
    fprintf(yyout, "%*cBreakStmt\n", level, ' ');
}

void ContinueStmt::output(int level)
{
    fprintf(yyout, "%*cContinueStmt\n", level, ' ');
}



// void CompoundStmt::output(int level)
// {
//     fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
//     stmt->output(level + 4);
// }
void CompoundStmt::output(int level)
{
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    if(stmt != nullptr){
        stmt->output(level + 4);
    }
    else{
        fprintf(yyout, "%*cNULL Stmt\n", level + 4, ' ');
    }
}


// void SeqNode::output(int level)
// {
//     fprintf(yyout, "%*cSequence\n", level, ' ');
//     stmt1->output(level + 4);
//     stmt2->output(level + 4);
// }
//q1解决seq支持数目过少的问题
void SeqNode::addNext(StmtNode* next)
{
    stmtList.push_back(next);
}
void SeqNode::output(int level)
{
    fprintf(yyout, "%*cSequence\n", level, ' ');
    for(auto stmt : stmtList){
        stmt->output(level + 4);
    }
}
//q8数组支持
void DimArray::addDim(ExprNode* next)
{
    dimList.push_back(next);
}
void DimArray::output(int level)
{
    fprintf(yyout, "%*cArray Dimension List\n", level, ' ');
    for(auto expr : dimList){
        expr->output(level + 4);
    }
}
//q9数组定义
void ArrayDef::addDef(ArrayDef* def)
{
    arrDefList.push_back(def);
}
void ArrayDef::output(int level)
{
    fprintf(yyout, "%*cArray Definition List\n", level, ' ');
    if(expr){
        expr->output(level + 4);
        return;
    }
    for(auto itm : arrDefList){
        itm->output(level + 4);
    }
}
//q9数组定义
// void ArrayItem::addExpr(ExprNode* exp)
// {
//     exprList.push_back(exp);
// }
// void ArrayItem::output(int level)
// {
//     // fprintf(yyout, "%*cArray Dimension List\n", level, ' ');
//     for(auto expr : exprList){
//         expr->output(level + 4);
//     }
// }


void DeclStmt::addDecl(Id* next, ExprNode *exp, DimArray *dim, ArrayDef *defList){
    idList.push_back(next);
    exprList.push_back(exp);
    dimArrayList.push_back(dim);
    defArrList.push_back(defList);
}
void DeclStmt::output(int level)
{
    for (size_t i = 0; i < idList.size(); i++)
    {
        fprintf(yyout, "%*c", level, ' ');
        // q2const常量支持
        //不对const另立节点类型，而是直接输出
        if(idList[i]->getSymbolEntry()->isConstant()){
            fprintf(yyout, "Constant\t");
        }
        // expr存在
        if(exprList[i]){
            fprintf(yyout, "DefStmt\n");
            idList[i]->output(level + 4);
            exprList[i]->output(level + 4);
        }else{
            fprintf(yyout, "DeclStmt\n");
            idList[i]->output(level + 4);
        }
        //q8数组支持
        if(dimArrayList[i]){
            dimArrayList[i]->output(level + 4);
        }
        //q9数组定义
        if(defArrList[i]){
            defArrList[i]->output(level + 4);
        }
    }
    
}
// void DefStmt::output(int level)
// {
//     fprintf(yyout, "%*c", level, ' ');
//     // q2const常量支持
//     //不对const另立节点类型，而是直接输出
//     if(id->getSymbolEntry()->isConstant()){
//         fprintf(yyout, "Constant\t");
//     }
//     fprintf(yyout, "DefStmt\n");
//     id->output(level + 4);
//     expr->output(level + 4);
// }

void IfStmt::output(int level)
{
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
}

void IfElseStmt::output(int level)
{
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

//q5参照if语句实现while循环
void WhileStmt::output(int level)
{
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');
    cond->output(level + 4);
    whileBodyStmt->output(level + 4);
}

// void ReturnStmt::output(int level)
// {
//     fprintf(yyout, "%*cReturnStmt\n", level, ' ');
//     retValue->output(level + 4);
// }
void ReturnStmt::output(int level)
{
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    if(retValue != nullptr){
        retValue->output(level + 4);
    }
    else{
        fprintf(yyout, "%*cVOID\n", level + 4, ' ');
    }
}

void AssignStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void FunctionDef::output(int level)
{
    std::string name, type;
    name = se->toStr();
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine function name: %s, type: %s\n", level, ' ', 
            name.c_str(), type.c_str());
    if(params){
        params->output(level + 4);
    }
    stmt->output(level + 4);
}
//q10添加参数列表
void FuncParam::addNext(StmtNode* next)
{
    paramList.push_back(next);
}
void FuncParam::output(int level)
{
    fprintf(yyout, "%*cParameters List\n", level, ' ');
    for(auto stmt : paramList){
        stmt->output(level + 4);
    }
}
